#!/usr/bin/env node
'use strict';

/**
 * Bundles the protocol layer into a single browser-loadable script.
 *
 * Renderer processes in Electron run sandboxed, so they cannot `require()` this
 * package directly. Emitting a standalone IIFE that assigns `globalThis.DWMProtocol`
 * lets a renderer share this package's protocol implementation verbatim, via an
 * ordinary `<script>` tag, with no sandbox weakening and no IPC round trips.
 */

const path = require('path');
const esbuild = require('esbuild');

const outfile = path.join(__dirname, '..', 'dist', 'dwm-protocol.browser.js');

esbuild
  .build({
    entryPoints: [path.join(__dirname, '..', 'src', 'browser.js')],
    bundle: true,
    format: 'iife',
    globalName: 'DWMProtocol',
    platform: 'browser',
    target: ['es2020'],
    outfile,
    banner: {
      js: '/* dwm-core protocol bundle - GENERATED by scripts/build-browser.js. Do not edit. */',
    },
    footer: {
      js: 'if (typeof module !== "undefined" && module.exports) { module.exports = DWMProtocol; }',
    },
  })
  .then(() => console.log(`Wrote ${path.relative(process.cwd(), outfile)}`))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
